// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAezU1KApAY_PQR6Dhv6szK1kRO7yI4Izo',
    appId: '1:450327839476:web:8a5a3731c4c0ea314954a1',
    messagingSenderId: '450327839476',
    projectId: 'weatherapp-f81db',
    authDomain: 'weatherapp-f81db.firebaseapp.com',
    storageBucket: 'weatherapp-f81db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnrfwtdE45fLnxEcoTAkXRyAgvCmn8E2w',
    appId: '1:450327839476:android:551677024ad76a0c4954a1',
    messagingSenderId: '450327839476',
    projectId: 'weatherapp-f81db',
    storageBucket: 'weatherapp-f81db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0PRRBCQeUqisAIoMd812keHnMVMznEL0',
    appId: '1:450327839476:ios:dd640454a57554434954a1',
    messagingSenderId: '450327839476',
    projectId: 'weatherapp-f81db',
    storageBucket: 'weatherapp-f81db.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0PRRBCQeUqisAIoMd812keHnMVMznEL0',
    appId: '1:450327839476:ios:dd640454a57554434954a1',
    messagingSenderId: '450327839476',
    projectId: 'weatherapp-f81db',
    storageBucket: 'weatherapp-f81db.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAezU1KApAY_PQR6Dhv6szK1kRO7yI4Izo',
    appId: '1:450327839476:web:5426d9ab28bb75994954a1',
    messagingSenderId: '450327839476',
    projectId: 'weatherapp-f81db',
    authDomain: 'weatherapp-f81db.firebaseapp.com',
    storageBucket: 'weatherapp-f81db.firebasestorage.app',
  );
}
